### ISSUE TITLE
Styling: inline switch

### ISSUE THREAD

**Issue by steffenbrem** [knownasilya/ember-cli-toggle#56]
By default the whole switch is filling my whole table cell and its centered. How would I make it inline and to the left?

**Comment by knownasilya** [comment]
Try styling it like so

```css
.x-toggle-component {
    justify-content: flex-start !important;
}
```
